### Importing Libraries

In [197]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics._regression import mean_absolute_error, mean_squared_error, root_mean_squared_error
from sklearn.preprocessing import StandardScaler

In [198]:
df = pd.read_csv( '../data/raw/Heart-Disease-Patients-Records.csv' )

In [199]:
df

,age,sex,chest_pain_type,resisting_blood_pressure,cholesterol_level,fasting_blood_sugar,rest_ecg,max_heart_rate_achieved,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,diagnosis
0,52,male,typical angina,125,212,lower than 120mg/ml,ST-T wave abnormality,168,no,1.0,downsloping,2,reversable defect,Diagnosed
1,53,male,typical angina,140,203,higher than 120mg/ml,normal,155,yes,3.1,upsloping,0,reversable defect,Diagnosed
2,70,male,typical angina,145,174,lower than 120mg/ml,ST-T wave abnormality,125,yes,2.6,upsloping,0,reversable defect,Diagnosed
3,61,male,typical angina,148,203,lower than 120mg/ml,ST-T wave abnormality,161,no,0.0,downsloping,1,reversable defect,Diagnosed
4,62,female,typical angina,138,294,higher than 120mg/ml,ST-T wave abnormality,106,no,1.9,flat,3,fixed defect,Diagnosed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,male,atypical angina,140,221,lower than 120mg/ml,ST-T wave abnormality,164,yes,0.0,downsloping,0,fixed defect,Un-Diagnosed
1021,60,male,typical angina,125,258,lower than 120mg/ml,normal,141,yes,2.8,flat,1,reversable defect,Diagnosed
1022,47,male,typical angina,110,275,lower than 120mg/ml,normal,118,yes,1.0,flat,1,fixed defect,Diagnosed
1023,50,female,typical angina,110,254,lower than 120mg/ml,normal,159,no,0.0,downsloping,0,fixed defect,Un-Diagnosed


In [200]:
df.sample()

,age,sex,chest_pain_type,resisting_blood_pressure,cholesterol_level,fasting_blood_sugar,rest_ecg,max_heart_rate_achieved,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,diagnosis
747,60,male,typical angina,117,230,higher than 120mg/ml,ST-T wave abnormality,160,yes,1.4,downsloping,2,reversable defect,Diagnosed


## Split features into X & y

In [201]:
df['diagnosis']=df['diagnosis'].map({'Un-Diagnosed': 0, 'Diagnosed': 1})

In [202]:
X = df.drop( columns = 'diagnosis' )
y = df['diagnosis']

In [203]:
X.shape

(1025, 13)

## Split into training & testing

In [204]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

# Model Selection

### Ensemble models

In [205]:
knn_model = KNeighborsRegressor( n_neighbors= 1 )

In [206]:
X_train.shape

(820, 13)

In [207]:
X_test.shape

(205, 13)

In [208]:
y_test

527    0
359    0
447    1
31     0
621    1
      ..
832    0
796    0
644    0
404    1
842    1
Name: diagnosis, Length: 205, dtype: int64

In [209]:
X = pd.get_dummies(X, drop_first=True)
X_train = X_train  # already split
X_test = X_test    # already split

In [210]:
# Convert categorical features
X = pd.get_dummies(X, drop_first=True)

# Now split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [211]:
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

In [212]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [213]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [214]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [215]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

KNeighborsClassifier()

In [216]:
knn_model.fit( X_train, y_train )

KNeighborsClassifier()

In [217]:
y_pred_train = knn_model.predict( X_train )
y_pred_train[:5]

array([1, 0, 0, 0, 0])

In [218]:
y_test[100:106]

464    0
107    1
629    1
576    0
254    1
723    0
Name: diagnosis, dtype: int64

In [219]:
y_pred_test[100:106]

array([1, 1, 0, 1, 1, 0])

In [220]:
pd.DataFrame({
    'Actual' : y_test[100:106],
    'Predicted' : y_pred_test[100:106],
    'Residuals' : y_test[100:106] - y_pred_test[100:106]
})

,Actual,Predicted,Residuals
464,0,1,-1
107,1,1,0
629,1,0,1
576,0,1,-1
254,1,1,0
723,0,0,0


## metrics

### MAE ( Mean Absolute Error ) ->  Look on the Avg. Error
### MSE ( Mean Squared Error )  ->  Triggers if there is high residuals (differences)
### RMSE ( Root Mean Squared Error ) -> Error between MAE & MSE

In [221]:
MAE_train = mean_absolute_error( y_train, y_pred_train )
MAE_test = mean_absolute_error( y_test, y_pred_test )

MSE_train = mean_squared_error( y_train, y_pred_train )
MSE_test = mean_squared_error( y_test, y_pred_test )

RMSE_train = root_mean_squared_error( y_train, y_pred_train )
RMSE_test = root_mean_squared_error( y_test, y_pred_test )

print( f'Mean Absolute Error of training : { MAE_train }' )
print( f'Mean Absolute Error of Testing : { MAE_test }' )
print(  )
print( f'Mean Squared Error of training : { MSE_train }' )
print( f'Mean Squared Error of Testing : { MSE_test }' )
print(  )
print( f'Root Mean Squared Error of Training : { RMSE_train }' )
print( f'Root Mean Squared Error of Testing : { RMSE_test }' )


Mean Absolute Error of training : 0.045121951219512194
Mean Absolute Error of Testing : 0.14146341463414633

Mean Squared Error of training : 0.045121951219512194
Mean Squared Error of Testing : 0.14146341463414633

Root Mean Squared Error of Training : 0.21241928165661467
Root Mean Squared Error of Testing : 0.3761162249014875


### Evaluation of previous n_neighbors = 5
**9.4, 136, 11.6**

### Calc. Cross Validation Score

In [222]:
cross_val_score( knn_model, X_train, y_train, cv= 4, scoring='neg_mean_squared_error').mean()

np.float64(-0.13048780487804879)

In [223]:
pd.set_option( 'display.max_columns', None)

## Curse of Dimensiality

## Fine Tuning

# Testing

In [224]:
df.sample()

,age,sex,chest_pain_type,resisting_blood_pressure,cholesterol_level,fasting_blood_sugar,rest_ecg,max_heart_rate_achieved,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,diagnosis
42,61,female,typical angina,130,330,lower than 120mg/ml,normal,169,no,0.0,downsloping,0,fixed defect,1


## Testing GridSearchCV on KNN Model

In [225]:
knn_model = KNeighborsRegressor(  )

In [226]:
gs_knn =  GridSearchCV(
    estimator= knn_model,
    param_grid= { 'n_neighbors' : [ 2, 3, 4, 5, 6, 7 ] }
)

In [227]:
gs_knn.fit( X_train, y_train )

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': [2, 3, 4, 5, 6, 7]})

In [228]:
gs_knn.best_params_

{'n_neighbors': 2}

In [229]:
y_test

527    0
359    0
447    1
31     0
621    1
      ..
832    0
796    0
644    0
404    1
842    1
Name: diagnosis, Length: 205, dtype: int64

In [230]:
y_pred_test

array([0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1])

In [231]:
knn_comparison_df = pd.DataFrame({
    'Actual (True)' : y_test,
    'Predicted (KNN)' : y_pred_test,
    'Residuals' : np.abs( y_test- y_pred_test )
})
knn_comparison_df

,Actual (True),Predicted (KNN),Residuals
527,0,0,0
359,0,0,0
447,1,1,0
31,0,0,0
621,1,1,0
...,...,...,...
832,0,0,0
796,0,0,0
644,0,0,0
404,1,1,0


In [232]:
knn_comparison_df

,Actual (True),Predicted (KNN),Residuals
527,0,0,0
359,0,0,0
447,1,1,0
31,0,0,0
621,1,1,0
...,...,...,...
832,0,0,0
796,0,0,0
644,0,0,0
404,1,1,0


## Visualize Residuals

In [233]:
px.line( knn_comparison_df.head( 25 ), x  = ['Actual (True)', 'Predicted (KNN)'] )

In [234]:
knn_comparison_df.head( 25 )

,Actual (True),Predicted (KNN),Residuals
527,0,0,0
359,0,0,0
447,1,1,0
31,0,0,0
621,1,1,0
590,0,0,0
905,1,1,0
737,1,1,0
76,0,0,0
948,1,1,0


In [235]:
px.histogram( knn_comparison_df, x  = ['Actual (True)', 'Predicted (KNN)'] )

<hr>

# [2] Linear Regression

In [236]:
from sklearn.linear_model import LinearRegression

In [237]:
lin_reg_model = LinearRegression()

In [238]:
os.cpu_count()

4

In [239]:
lin_reg_model.fit( X_train, y_train )

LinearRegression()

In [240]:
y_pred_train_lr = lin_reg_model.predict( X_train )
y_pred_test_lr = lin_reg_model.predict( X_test )

In [241]:
y_pred_train_lr

array([ 0.40944495,  0.3519544 , -0.09419155,  0.65990946,  0.3430496 ,
        0.28269251,  0.9084041 , -0.06124065,  0.5721576 ,  0.72647723,
        0.91731021,  0.42995199,  0.73618183,  0.43010012,  1.04230332,
        0.19409904,  0.86829133,  0.97652092,  0.06749816,  0.10586069,
        0.26620951,  0.05341319,  0.22053153,  1.02548271,  0.48489225,
        0.30675859,  0.52285545,  0.48742957,  0.34209495,  0.77459838,
        0.77723967,  0.70218765,  0.73036746,  0.0750229 ,  0.38637786,
        0.66094426,  0.21345393,  0.0826049 ,  0.888574  ,  0.90022133,
        0.47717072,  0.87068774,  0.61250877,  0.34301695,  0.85204964,
        0.0656481 ,  0.82360603,  0.67214201,  1.41545379,  0.67996061,
        0.02665806,  0.92305662,  0.56356743,  1.08475973,  0.11932482,
        0.94974336,  0.50948947,  0.20880218,  0.93283655,  0.60628654,
        1.0397564 ,  1.09727128, -0.16274338,  0.91731021,  0.45239616,
        0.92305662,  0.31874998,  0.57427574,  0.25491657,  0.94

In [242]:
y_train

835    1
137    0
534    0
495    0
244    0
      ..
700    0
71     1
106    1
270    0
860    1
Name: diagnosis, Length: 820, dtype: int64

# Intercept -> b

In [243]:
lin_reg_model.intercept_

np.float64(0.4841463414634146)

In [244]:
X_train.shape

(820, 19)

In [245]:
lin_reg_model.coef_

array([ 0.00071559,  0.02276615,  0.03716604, -0.05045365,  0.07474414,
        0.096125  ,  0.07251888,  0.02748495,  0.0258459 ,  0.13999333,
        0.00162942,  0.01109634,  0.01859879,  0.04512664,  0.05936356,
        0.00045544, -0.23605243, -0.10262111, -0.11656485])

## Y = b + p1x1 + p2x2 + p3x3 + p4x4 +  .......... p24x24

In [246]:
print( 'Linear Regression Evaluation :' )
print( '-------------------------' )
print(  )

MAE_train = mean_absolute_error( y_train, y_pred_train_lr )
MAE_test = mean_absolute_error( y_test, y_pred_test_lr )

MSE_train = mean_squared_error( y_train, y_pred_train_lr )
MSE_test = mean_squared_error( y_test, y_pred_test_lr )

RMSE_train = root_mean_squared_error( y_train, y_pred_train_lr )
RMSE_test = root_mean_squared_error( y_test, y_pred_test_lr )

print( f'Mean Absolute Error of training : { MAE_train }' )
print( f'Mean Absolute Error of Testing : { MAE_test }' )

print(  )
print( f'Mean Squared Error of training : { MSE_train }' )
print( f'Mean Squared Error of Testing : { MSE_test }' )
print(  )
print( f'Root Mean Squared Error of Training : { RMSE_train }' )
print( f'Root Mean Squared Error of Testing : { RMSE_test }' )

Linear Regression Evaluation :
-------------------------

Mean Absolute Error of training : 0.2527933219828091
Mean Absolute Error of Testing : 0.29395415754001175

Mean Squared Error of training : 0.10774400325163407
Mean Squared Error of Testing : 0.14240487295525858

Root Mean Squared Error of Training : 0.3282438167759357
Root Mean Squared Error of Testing : 0.3773657018798324


### Model Serialization ( Saving ) ( Dumping )
#### Save to extension .pkl

In [247]:
import joblib
import pickle

In [248]:
lin_reg_model

LinearRegression()

In [249]:
os.listdir( '../artifacts' )

['parkinson_model.pkl', 'svm_pipeline.pkl']

In [292]:
joblib.dump( lin_reg_model, '../Artifacts/linearRegression.pkl' )

['../Artifacts/linearRegression.pkl']

In [251]:
df.sample()

,age,sex,chest_pain_type,resisting_blood_pressure,cholesterol_level,fasting_blood_sugar,rest_ecg,max_heart_rate_achieved,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,diagnosis
384,35,male,typical angina,126,282,lower than 120mg/ml,normal,156,yes,0.0,downsloping,0,reversable defect,1


In [252]:
df.shape

(1025, 14)

### Define a function to evaluate any regressor

In [253]:
#### model

<h3>Import a colorama library for styling the color of words and paragraphs

<h4> Fore Stands to foreground color

In [254]:
from colorama import Fore

In [255]:
print(  Fore.GREEN + 'hello' )

hello


In [256]:
def evaluate_regressor( model, model_name: str ,X_train, X_test, y_train, y_test  ) :
    
    print( 'Training.........' + '\n' )
    
    print( model_name + ':' )
    print( '-'*20 )
    
    model.fit( X_train, y_train ) # Training !
    y_pred_train = model.predict( X_train )
    y_pred_test = model.predict( X_test )

    print(  )

    MAE_train = mean_absolute_error( y_train, y_pred_train )
    MSE_train = mean_squared_error( y_train, y_pred_train )
    
    RMSE_train = root_mean_squared_error( y_train, y_pred_train )
    
    MAE_test = mean_absolute_error( y_test, y_pred_test )
    MSE_test = mean_squared_error( y_test, y_pred_test )
    RMSE_test = root_mean_squared_error( y_test, y_pred_test )

    print( f'Mean Absolute Error of training : { MAE_train }' )
    print( Fore.WHITE + f'Mean Absolute Error of Testing : { MAE_test }' )
    print(  )

    print( Fore.CYAN + f'Mean Squared Error of training : { MSE_train }' )
    print( Fore.RED  + f'Mean Squared Error of Testing : { MSE_test }' )
    print(  )

    print( Fore.WHITE + f'Root Mean Squared Error of Training : { RMSE_train }' )
    print( Fore.WHITE + f'Root Mean Squared Error of Testing : { RMSE_test }' )


## [1] KNN

In [257]:
knn_model = KNeighborsRegressor( n_neighbors=7 )

In [258]:
evaluate_regressor( knn_model, 'K Neighbors Regressor', X_train, X_test, y_train, y_test )

Training.........

K Neighbors Regressor:
--------------------

Mean Absolute Error of training : 0.13832752613240418
Mean Absolute Error of Testing : 0.1735191637630662

Mean Squared Error of training : 0.0637630662020906
Mean Squared Error of Testing : 0.09527127924340469

Root Mean Squared Error of Training : 0.252513497069148
Root Mean Squared Error of Testing : 0.30866045947514026


## [2] Linear Regression 

In [259]:
lin_reg_model = LinearRegression()

In [260]:
evaluate_regressor( lin_reg_model, 'Linear Regression without regularization', X_train, X_test, y_train, y_test  )

Training.........

Linear Regression without regularization:
--------------------

Mean Absolute Error of training : 0.2527933219828091
Mean Absolute Error of Testing : 0.29395415754001175

Mean Squared Error of training : 0.10774400325163407
Mean Squared Error of Testing : 0.14240487295525858

Root Mean Squared Error of Training : 0.3282438167759357
Root Mean Squared Error of Testing : 0.3773657018798324


## [3] Linear Regression with regularization L1 ( Lasso )

In [261]:
lin_reg_L1 = Lasso( alpha = 0.2 )

In [262]:
evaluate_regressor( lin_reg_L1, 'Linear Regression with REGULARIZATION ( L1 )', X_train, X_test, y_train, y_test )

Training.........

Linear Regression with REGULARIZATION ( L1 ):
--------------------

Mean Absolute Error of training : 0.44954632580323456
Mean Absolute Error of Testing : 0.45441170854050067

Mean Squared Error of training : 0.2058821237885347
Mean Squared Error of Testing : 0.21043162436921264

Root Mean Squared Error of Training : 0.4537423539725322
Root Mean Squared Error of Testing : 0.4587282685525415


## [4] Linear Regression with regularization L2 ( Ridge )

In [263]:
ridge = Ridge(  )

In [264]:
ridge.fit(X_train, y_train)

Ridge()

In [265]:
ridge.coef_

array([ 0.00082478,  0.02263794,  0.0369749 , -0.050161  ,  0.07459466,
        0.09583275,  0.07258673,  0.02692272,  0.02516996,  0.13951437,
        0.00103177,  0.01110053,  0.01830138,  0.04543445,  0.05966787,
        0.00043815, -0.19549999, -0.08270851, -0.07694665])

In [266]:
evaluate_regressor( ridge, 'Linear Regression with REGULARIZATION ( L2 )', X_train, X_test, y_train, y_test)

Training.........

Linear Regression with REGULARIZATION ( L2 ):
--------------------

Mean Absolute Error of training : 0.25292921413070324
Mean Absolute Error of Testing : 0.2934498303343769

Mean Squared Error of training : 0.10775955822039514
Mean Squared Error of Testing : 0.14135985802066817

Root Mean Squared Error of Training : 0.32826751015047945
Root Mean Squared Error of Testing : 0.37597853398920017


## [5] Support Vector Machine

In [267]:
from sklearn.svm import SVR

In [268]:
svm_regressor = SVR(  )

In [269]:
evaluate_regressor( svm_regressor, 'SVM', X_train, X_test, y_train, y_test  )

Training.........

SVM:
--------------------

Mean Absolute Error of training : 0.11218780937116321
Mean Absolute Error of Testing : 0.15408365940033886

Mean Squared Error of training : 0.026121632760660898
Mean Squared Error of Testing : 0.05403757406227727

Root Mean Squared Error of Training : 0.1616218820601372
Root Mean Squared Error of Testing : 0.23245983322345662


## [6] Support Vector Machine with Scaling

In [270]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR


In [271]:
svm_pipeline = make_pipeline(StandardScaler(), SVR())

In [272]:
svm_pipeline

Pipeline(steps=[('standardscaler', StandardScaler()), ('svr', SVR())])

In [273]:
import joblib
import pickle

In [ ]:
joblib.dump(svm_pipeline, '../Artifacts/svm_pipeline.pkl')

['../app/artifacts/svm_pipeline.pkl']

In [275]:
evaluate_regressor( svm_pipeline, 'SVM With Scaling', X_train, X_test, y_train, y_test)

Training.........

SVM With Scaling:
--------------------

Mean Absolute Error of training : 0.1121878093711631
Mean Absolute Error of Testing : 0.15408365940033886

Mean Squared Error of training : 0.02612163276066086
Mean Squared Error of Testing : 0.05403757406227726

Root Mean Squared Error of Training : 0.16162188206013708
Root Mean Squared Error of Testing : 0.2324598332234566


### Try Fine-Tuning

<h3> if kernel == 'poly' --> higher degree --> pruning overfitting 

<h3>if gamma small -->Try not to fit all data --> high error --> underfitting
<h3> if gamma high --> FIT all the data as possible --> low error --> Overfitting

In [288]:
svm_model=SVR(gamma=0.2, C=0.5)

In [289]:
gs_svm=GridSearchCV(
    svm_regressor,
    param_grid={
    'gamma':[0.2,0.4,0.5,0.7],
    'C':[0.2,0.4,0.5,0.7]
    })


<h3> Train X and Y for all combinations
<h4> Takes much time around 10-15 mins

In [290]:
gs_svm.fit(X_train,y_train)

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.2, 0.4, 0.5, 0.7],
                         'gamma': [0.2, 0.4, 0.5, 0.7]})

In [291]:
gs_svm.best_params_

{'C': 0.7, 'gamma': 0.4}